sudo: required

before_install:
- sudo apt-get update 
- sudo apt-get install texlive-latex-extra latexmk texlive-lang-german

script:
- latexmk -pdf -interaction=nonstopmode main.tex

deploy:
  - provider: script
    script:
      - latexmk -pdf -interaction=nonstopmode main.tex
      - git add -f main.pdf
      - git commit -m "build pdf"
      - git push -f https://sgeisler:$GITHUB_TOKEN@github.com/sgeisler/rechnernetze.git HEAD:gh-pages
    on:
      branch: master
