sudo: required

before_install:
- sudo apt-get update 
- sudo apt-get install texlive-latex-extra latexmk texlive-lang-german

script:
- latexmk -pdf -interaction=nonstopmode main.tex

deploy:
  - provider: script
    script: ./deploy.sh
    on:
      branch: master
